name: Auto Update Node.js

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest Node.js version
        run: |
          latest_version=$(curl -s https://nodejs.org/dist/index.json | jq -r '.[0].version')
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Create directories if they don't exist
        run: |
          mkdir -p client backend

      - name: Update .nvmrc files
        run: |
          echo "$LATEST_VERSION" > client/.nvmrc
          echo "$LATEST_VERSION" > backend/.nvmrc
