name: Auto Update Node.js

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest Node.js Version
        id: node_version
        run: |
          latest_version=$(curl -s https://nodejs.org/dist/index.json | jq -r '.[0].version')
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Update Node.js Version in .nvmrc (Frontend, Backend)
        run: |
          for dir in client backend; do
            if [ -d "$dir" ]; then
              echo "$LATEST_VERSION" > "$dir/.nvmrc"
            fi
          done

      - name: Update Node.js Version in package.json (Frontend, Backend, Server)
        run: |
          for dir in client backend server; do
            if [ -f "$dir/package.json" ]; then
              sed -i "s/\"node\": \".*\"/\"node\": \"$LATEST_VERSION\"/" "$dir/package.json"
            fi
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add client/.nvmrc backend/.nvmrc server/.nvmrc
          git add client/package.json backend/package.json server/package.json
          git commit -m "Updated Node.js version to $LATEST_VERSION in frontend, backend, and server"
          git push
